dataset:
  name: Helsinki-NLP/opus-100
  source_lang: en
  subset: en-ru
  target_lang: ru
  text_column: translation
device: cuda
model:
  checkpoint: null
  embedding_model_name: intfloat/multilingual-e5-small
  max_length: 512
  model_name: Helsinki-NLP/opus-mt-en-ru
  tokenizer_name: Helsinki-NLP/opus-mt-en-ru
training:
  bf16: true
  deepspeed: ds_config.json
  early_stopping_patience: 30
  early_stopping_threshold: 0.01
  epochs: 3
  eval_accumulation_steps: 10
  eval_batch_size: 4
  eval_steps: 50
  gradient_accumulation_steps: 2
  learning_rate: 5.0e-05
  logging_steps: 10
  max_grad_norm: 1.0
  metric_for_best_model: meteor
  save_steps: 50
  training_batch_size: 64
  warmup_steps: 100
  weight_decay: 0.01
