dataset:
  name: "Helsinki-NLP/opus-100"
  subset: "en-ru"
  text_column: "translation"
  source_lang: "en"
  target_lang: "ru"

model:
  name: "TinyLlama/TinyLlama_v1.1"
  max_length: 512

training:
  batch_size: 16
  epochs: 3
  learning_rate: 5e-5
  warmup_steps: 100
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0

tokenizer:
  max_length: 512

device: "cuda"