dataset:
  name: "Helsinki-NLP/opus-100"
  subset: "en-ru"
  text_column: "translation"
  source_lang: "en"
  target_lang: "ru"

model:
  name: "TinyLlama/TinyLlama_v1.1"
  max_length: 512

training:
  training_batch_size: 16
  eval_batch_size: 4
  epochs: 3
  learning_rate: 5e-5
  warmup_steps: 100
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  weight_decay: 0.01
  logging_steps: 10
  eval_steps: 50
  save_steps: 50
  bf16: true
  eval_accumulation_steps: 10
  metric_for_best_model: "bleu" 
  early_stopping_patience: 10
  early_stopping_threshold: 0.01
  deepspeed: "ds_config.json"


tokenizer:
  max_length: 512
  tokens:
    en: "[EN]"
    ru: "[RU]"

device: "cuda"